### ISSUE TITLE
Server doesn't run

### ISSUE THREAD

**Issue by mickjol** [bykof/cordova-plugin-webserver#1]
I install your plugin in my cordova project
I run my application, on an Android 7
Inside my deviceReady, I initiate the onRequest and start the server without error.

webserver.onRequest(this.onRequest.bind(this));
webserver.start();

But I can't access to the server 

I try, in chrome on the phone itself : http://127.0.0.1/ and http://localhost/
and I try, from my computer : http://myipaddress/

**Comment by bykof** [comment]
You have to access your server via http://127.0.0.1:8080
See here: https://github.com/bykof/cordova-plugin-webserver#startport

**Comment by mickjol** [comment]
Yes, I just forget to put in my comment.

**Comment by bykof** [comment]
So you are using http://127.0.0.1:8080 to access your server and it does not work? 
Can you maybe post your whole code especially where you handle request and do the response.

**Comment by mickjol** [comment]
webserver.onRequest(function(request) {
      console.log('request is trigger');
    });

For now this is the only code I had.
But I always receive a "net::ERR_CONNECTION_REFUSED"
And I never pass in my callback function

**Comment by mickjol** [comment]
Maybe I need to install something for NanoHttpd ?

**Comment by bykof** [comment]
No, the NanoHttd is native code in a library which you download when you install the plugin. 

1.
Have a look in the plugins/cordova-plugin-webserver/src folder, is there a folder called `android`?
And are there two files in this folder?
- Webserver.java
- NanoHTTPDWebserver.java

2.
Does your code look like this?
In the index.html file try this:

```javascript
<html>
  <body>
    <script type="text/javascript">
      function runServer() {
        webserver.onRequest(
          function(request) {
            console.log("This is the request: ", request);

            webserver.sendResponse(
              request.responseId,
              {
                status: 200,
                body: '<html>Hello World</html>',
                headers: {
                  'Content-Type': 'text/html'
                }
              }
            );
          }
        );
        
        webserver.start();
      }
      
      // This is really important! 
      document.addEventListener("deviceready", runServer, false);
    </script>
  </body>
</html>


```

**Comment by bykof** [comment]
@mickjol what is your status?

**Comment by mickjol** [comment]
Yes, every look the same.
And I can saw the "webserver" object in the DEV console,  without error

**Comment by bykof** [comment]
then try to paste the code in the DEV console and try access your webserver again via  http://127.0.0.1:8080.

**Comment by mickjol** [comment]
I find a way to use it, but I need to install another plugin ?

When I install "cordova-plugin-httpd" the server receive the request, but the browser doesn't receive the response.

**Comment by bykof** [comment]
This is impossible, my plugin is standalone so you don't need any extra plugins...

Ok look, I tried following things: 
1. Created a new phonegap project (you could also use cordova)
`phonegap create test`

2. Then I installed the plugin:
`cordova plugin add https://github.com/bykof/cordova-plugin-webserver`

3. Then I added iOS Support
`phonegap platform add ios`

4. Then I copied my code into the index.html of the www dir in the phonegap project
```
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="msapplication-tap-highlight" content="no" />
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />
    <!-- This is a wide open CSP declaration. To lock this down for production, see below. -->
    <meta http-equiv="Content-Security-Policy" content="frame-src * gap://ready; default-src 'self' gap://ready file://* *; connect-src * blob: data:; style-src * 'unsafe-inline'; script-src * 'unsafe-eval' 'unsafe-inline'; img-src data: *">
    <link rel="stylesheet" type="text/css" href="css/index.css" />
    <title>Hello World</title>
    <script src="cordova.js" type="text/javascript"></script>
</head>

<body>
  <script type="text/javascript">
    function runServer() {
      webserver.onRequest(
        function(request) { 

          webserver.sendResponse(
            request.responseId,
            {
              status: 200,
              body: '<html>Hello World</html>',
              headers: {
                'Content-Type': 'text/html'
              }
            }
          );
        }
      );

      webserver.start();
    }

    // This is really important!
    document.addEventListener("deviceready", runServer, false);
  </script>
</body>

</html>

```

**5. Started the app and saw our fault...**


In my code example we use request.responseId, but I you look in my documentation, a request object look like this:
```
{
	requestId: '3jh4-ku34k-k3j4k-k3j42',
	body: '',
	headers: {
		... some headers
	},
	method: 'POST',
	path: '/hello/world',
	query: 'bla=wer&blu=2'
}
```

So just change 
```
webserver.sendResponse(
  request.responseId,
  {
    status: 200,
    body: '<html>Hello World</html>',
    headers: {
      'Content-Type': 'text/html'
    }
  }
);
```

in 

```
webserver.sendResponse(
  request.requestId,
  {
    status: 200,
    body: '<html>Hello World</html>',
    headers: {
      'Content-Type': 'text/html'
    }
  }
);
```

and it will work. Sorry for the circumstances. I will correct my README.md example.

**Comment by mickjol** [comment]
I use cordova.

I just create a new cordova project.
Add the android platform
Add your plugin
Run the project on my phone
Run the code inside DEV console

And when I try to access it in browser. I receive the ERR_CONNECTION_REFUSED

**Comment by mickjol** [comment]
OK, I check the dependencies and I finally find.

When I install the plugin, the "universal-router" doesn't include.
So I install it and everything work fine.

npm install universal-router

**Comment by bykof** [comment]
**Lol?** That does not supposed to be!
It's because of the src/www/appserver/AppServer directory, where I commited some boilerplate code. You probably using a bundler with an es6 compiler and it tries to resolve the imports.I will delete this directory so you don't have to install the "universal-router" library. Anyway "appserver" not a part of this project. Thank you for your hint

Ok right, so if you are done, please close the issue and have a lot of fun programming with cordova--plugin-webserver :)
