### ISSUE TITLE
Can I share my files from mobile to pc?

### ISSUE THREAD

**Issue by merbin2012** [bykof/cordova-plugin-webserver#14]
I am seen many app, that allow user to share there mobile files to pc through local ip address, can I use this plugin for that purpose?

**Comment by captainreptile** [comment]
The web-server has no actual root folder like apache that serves files from.
Instead you will be sitting on the core functionality of the server it self - dealing with requests.

Disclaimer: I didn't use the module yet, info based on document and code

**Comment by bykof** [comment]
As in https://github.com/bykof/cordova-plugin-webserver/issues/13 explained. You should combine FileReader API of Cordova to serve any files.
