### ISSUE TITLE
Default name to ip

### ISSUE THREAD

**Issue by SainathThota** [bykof/cordova-plugin-webserver#16]
I would like to giva a name to ip so that i can give a fixed name for requesting devices

ex if url is http://23.45.67.56:8080 need to call like http://somename:8080

**Comment by bykof** [comment]
This is only possible if you setup a domain for your ip...
You can do this by setup a hostname in the /etc/hosts file of every requesting device or setup your DHCP Server (Router) to resolve the given domain to a specific ip.

Reference:
https://unix.stackexchange.com/questions/16890/how-to-make-a-machine-accessible-from-the-lan-using-its-hostname
