### ISSUE TITLE
Cannot find module 'cordova/exec' 

### ISSUE THREAD

**Issue by waidp521** [bykof/cordova-plugin-webserver#19]
when perform webserver.js,   i   got  the error "Cannot find module 'cordova/exec' "    please help me,3q.

**Comment by bykof** [comment]
This problem is not a part of my plugin... this is not an ionic2 support board, so please investigate "cordova" or "ionic" errors by yourself. 

Anyway try this: https://stackoverflow.com/questions/43079195/cannot-find-module-cordova-exec-in-ionic-2
