### ISSUE TITLE
Can I access this webserver via an HTTP request?

### ISSUE THREAD

**Issue by rtm** [bykof/cordova-plugin-webserver#21]
Can I access this webserver via an HTTP request? In other words, does it have a "host name"?

**Comment by kukukk** [comment]
Hi!
A webserver doesn't have a "host name". The device can have a "host name", and it depends on your configuration and your network. If the device is connected to a WiFi network you can access the webserver using http://IP:PORT>, where IP is your device's IP address and the PORT is what you specified in the start(port) method.

**Comment by bykof** [comment]
Yep, as @kukukk said. You do not have a hostname, because a hostname is something which comes from the provider. 
You can access your webserver by entering the IP of the device in your local network.
