### ISSUE TITLE
not able to run on IOS

### ISSUE THREAD

**Issue by rahulsu** [bykof/cordova-plugin-webserver#27]
I add plugin, added platform, and when I try to run I see the below error messages.

$ cordova run ios
Script file does't exist and will be skipped: /Users/xxxx/project/bykof/cordova-plugin-webserver/WISPr/plugins/cordova-plugin-add-swift-support/add-swift-support.js
Building project: /Users/xxxx/project/bykof/cordova-plugin-webserver/WISPr/platforms/ios/HelloCordova.xcworkspace
	Configuration: Debug
	Platform: device
User defaults from command line:
    IDEArchivePathOverride = /Users/xxxx/project/bykof/cordova-plugin-webserver/WISPr/platforms/ios/HelloCordova.xcarchive

Build settings from command line:
    CONFIGURATION_BUILD_DIR = /Users/xxxx/project/bykof/cordova-plugin-webserver/WISPr/platforms/ios/build/device
    SHARED_PRECOMPS_DIR = /Users/xxxx/project/bykof/cordova-plugin-webserver/WISPr/platforms/ios/build/sharedpch

Build settings from configuration file '/Users/xxxx/project/bykof/cordova-plugin-webserver/WISPr/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

error: archive not found at path '/Users/xxxx/project/bykof/cordova-plugin-webserver/WISPr/platforms/ios/HelloCordova.xcarchive'
** EXPORT FAILED **

CordovaError: Promise rejected with non-error: 'Error code 65 for command: xcodebuild with args: -exportArchive,-archivePath,HelloCordova.xcarchive,-exportOptionsPlist /Users/xxxx/project/bykof/cordova-plugin-webserver/WISPr/platforms/ios/exportOptions.plist,-exportPath,/Users/xxxx/project/bykof/cordova-plugin-webserver/WISPr/platforms/ios/build/device'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:30:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by boedy** [comment]
Please try again with latest version. If that doesn't work I recommend removing your `plugins` and 'platforms` directory. This will probably solve your issue.
