### ISSUE TITLE
sendFileResponse is not a function

### ISSUE THREAD

**Issue by bknill** [bykof/cordova-plugin-webserver#28]
Hi, 

sendFileResponse is not a function. Is this feature added (on Android) ?

**Comment by bykof** [comment]
There is no sendFileResponse feature yet.

**Comment by bloigge** [comment]
I stumbled across this as well - the function is listed in the README.

![image](https://user-images.githubusercontent.com/7089726/51677793-05603200-1fdb-11e9-8446-0b67d16902f9.png)

**Comment by boedy** [comment]
As long as this method is not implemented it should not be in the documentation. I recommend moving that code to a separate feature branch.

**Comment by boedy** [comment]
Serving file responses now possible on both iOS and Android. Check the [README.md](https://github.com/bykof/cordova-plugin-webserver/blob/master/README.md) for details.
