### ISSUE TITLE
Filesystem?

### ISSUE THREAD

**Issue by arjunmenon** [bykof/cordova-plugin-webserver#3]
Hey
Does this allow accessing the filesystem?

If that is the case, there should be a form of authentication. Maybe a key/value token, allowing limited access.
Also an option like accessing types of files, images, mp3s, etc only should be allowed.

**Comment by bykof** [comment]
No this doesn't allow filesystem access... because you define HTTP endpoints which will be called. If you want to serve files or other things you can do this with cordova-plugins or cordova-api only. 
So in conclusion, there is no need for protection.
