### ISSUE TITLE
Unable to configure root directory

### ISSUE THREAD

**Issue by haipingzi** [bykof/cordova-plugin-webserver#30]
Our project requirement is to access a local directory resource offline, but the plug-in can't meet the requirement now. Can we improve it?

**Comment by bykof** [comment]
Sure, make a pull request

**Comment by haipingzi** [comment]
Did you solve this problem?

**Comment by bykof** [comment]
This is an open source project. I am working and doing my master... I don't have any time to work on this. If you want the feature, build it and create a pull request. Otherwise I can't help you, sorry.

**Comment by boedy** [comment]
@haipingzi There is another plugin [cordova-httpd](https://github.com/floatinghotpot/cordova-httpd) which serves files directly from a webroot. That might fit your requirement better.
