### ISSUE TITLE
Not work with ionic2

### ISSUE THREAD

**Issue by oenlighteno** [bykof/cordova-plugin-webserver#4]
When i test with pure cordova it work, but when i test with ionic cordova it not work.
How to fix this?

**Comment by bykof** [comment]
Okay I have tried it now. Sorry for the long delay. 
1. I started a new project with `ionic start ` and choosed "blank template".
2. Install the plugin: `ionic cordova plugin add https://github.com/bykof/cordova-plugin-webserver`
3. Open main.ts and type at the end of the file 
```javascript
webserver.onRequest(
	function(request) {
		console.log("O MA GAWD! This is the request: ", request);

		webserver.sendResponse(
			request.requestId,
			{
				status: 200,
				body: '<html>Hello World</html>',
				headers: {
					'Content-Type': 'text/html'
				}
			}
		);
	}
);

webserver.start();

//... after a long long time
// stop the server
webserver.stop();
```

**Comment by oenlighteno** [comment]
Thank you for your tryed. Thank you so much
Do you mean end of file, that mean outer class bracket?

เมื่อ 29 พ.ย. 2017 6:00 หลังเที่ยง "Michael Bykovski" <
notifications@github.com> เขียนว่า

**Comment by bykof** [comment]
I mean, that you cant access webserver in typescript by default. You have to save it with this statement: 
```
const webserver = window['plugins']['webserver'];
```

**Comment by oenlighteno** [comment]
ok thank you.

2017-11-29 19:15 GMT+07:00 Michael Bykovski <notifications@github.com>:

**Comment by NickStrupat** [comment]
i get 
```
Runtime Error
undefined is not an object (evaluating 'window['plugins']['webserver']')
```
when i am trying to access `window['plugins']['webserver']` in `main.ts`

**Comment by waidp521** [comment]
@NickStrupat i get the same error
@bykof please help me to solve this,  i was confused many days.  thank you

**Comment by bykof** [comment]
Have you tried this: https://stackoverflow.com/questions/45080622/ionic-how-to-access-a-cordova-plugin 
@waidp521 @NickStrupat

**Comment by saberprashant** [comment]
Hey @bykof ,  still it isn't working with ionic 2. I tried mostly everything, but nothing starts. I get some errors on inspecting it, saying that plugin isn't installed, but I correctly installed it with your repo and directly as well.  
Please help.
