### ISSUE TITLE
Minimum cordova version

### ISSUE THREAD

**Issue by Huiting-Yeong** [bykof/cordova-plugin-webserver#6]
I am seeing in plugin.xml:

    <engine name="cordova" version=">=7.0.0" />

whereas in package.json it is

    "cordova": "^6.1.1"

Must cordova be greater than `7.0.0` or is it compatible with `6.1.1` as well?

**Comment by bykof** [comment]
I think I started to write the package with 6.1.1 and then upgraded it to 7.0.0.

So in a nutshell: It's compatible with 6.1.1, yes

**Comment by bykof** [comment]
@Huiting-Yeong but I think it's better to improve users by forcing them to use the newest cordova version. So better I leave the code as it is. :D
