### ISSUE TITLE
How to Handle Multiple request with this webserver

### ISSUE THREAD

**Issue by Gunasekaran15** [bykof/cordova-plugin-webserver#8]
how  to handle  multiple request  with  this  webserver

**Comment by bykof** [comment]
As far as I know, multiple requests are supported o.O
Do you experienced a different behaviour?

**Comment by Gunasekaran15** [comment]
If you don't mind please give me a  example code  to  handle multiple requests  and  responses,  Because  I  don't  know  to  write  multiple  response  for different requests

**Comment by bykof** [comment]
Ehm.. if you don't know how to use the project, you should maybe start with easier things like node.js or python (flask)... 
This project is quite a basic request-response handler.
I will note provide you examples, because my example above is sufficient.

**Comment by bykof** [comment]
Dude, try maybe if or switch statements? 
How long are you already programming?
As I told you this is a pretty basic project which is doing only request-response. If you don't know how to use it, start with easier things like http://expressjs.com/ or https://flask-socketio.readthedocs.io/en/latest/. 
These projects does not work on mobile devices but will give you a good introduction in request-response systems.
